#!env zsh
####
# When using gnu ls, inject --group-directories-first --quoting-style=literal to the alias
####

if [[ "${OSTYPE}" =~ "^linux" ]] || [[ ${${(s#/#)${(s# -> #)$(which -ps ls)[-1]}}[-1]} == "gls" ]]; then
  echo "ls --group-directories-first --quoting-style=literal"
fi

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
