#!/bin/sh

# detect administrators
[ ${UID:-999} -eq 0 ] && WANT_SBIN=1
[ $(groups | grep -c admin) -gt 0 ] && WANT_SBIN=1

# check for binary
[ "${WANT_SBIN:-0}" -gt 0 ] && [ -n "$(which zfs 2> /dev/null)" ] && echo "sudo zfs"

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
