#!/bin/sh

# detect administrators
[ ${UID:-999} -eq 0 ] && WANT_SBIN=1
[ $(groups | grep -c staff) -gt 0 ] && WANT_SBIN=1
[ $(groups | grep -c sysadmin) -gt 0 ] && WANT_SBIN=1

# add /usr/sbin if wanted
[ $(echo "${PATH}" | grep -c "/usr/sbin:")  -eq 0 ] &&  \
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="${PATH}:/usr/sbin"

# check for gnu
PATH="$(echo "${PATH}" | /bin/sed -r 's#:/usr/gnu/s?bin##g')"
if [ -d "/usr/gnu" ]; then
  PATH="${PATH}:/usr/gnu/bin"
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="${PATH}:/usr/gnu/sbin"
fi

# check for pkgsrc (smartos)
PATH="$(echo ${PATH} | /bin/sed -r 's#/opt/local/s?bin:##g')"
if [ -d "/opt/local" ]; then
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="/opt/local/sbin:${PATH}"
  PATH="/opt/local/bin:${PATH}"
fi

# check for omniti repository (omnios)
PATH="$(echo ${PATH} | /bin/sed -r 's#/opt/omni/s?bin:##g')"
if [ -d "/opt/omni" ]; then
  PATH="${PATH}:/opt/omni/bin"
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="${PATH}:/opt/omni/sbin"
fi

# check for /usr/local
PATH="$(echo ${PATH} | /bin/sed -r 's#/usr/local/s?bin:##g')"
if [ -d "/usr/local" ]; then
  PATH="/usr/local/bin:${PATH}"
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="/usr/local/sbin:${PATH}"
fi

# check for opencsw
PATH="$(echo ${PATH} | /bin/sed -r 's#:/opt/csw/s?bin##g')"
if [ -d "/opt/csw" ]; then
  PATH="${PATH}:/opt/csw/gnu:/opt/csw/bin"
  [ "${WANT_SBIN:-0}" -gt 0 ] && PATH="${PATH}:/opt/csw/sbin"
fi

## add ${HOME}/.bin
[[ -e "${HOME}/.bin" ]] && PATH="${PATH}:${HOME}/.bin"

# return new PATH
echo "${PATH}"

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2
